- README.md
- specificatie/openapi.yaml
We implementeren de (omgekeerde) "van" relatie tussen zakelijkrecht en tenaamstelling als gegevensgroep zodat de tenaamstelling als groeps-element opgenomen wordt en niet als embedded subresource. -- resourcenaam = zakelijkrechttenaamstelling
Ik maak een API-versie tot aan de tenaamstelling. Persoon wordt niet embed. Dat is voor de eerste develop-sprint.
> OpenAPI.Yaml aangepat n.a.v. afsprakend 8-05-2019

- specificatie/BRK-Bevragen/openapi.yaml
- Parameter typegerechtigde op koz is string bij waardelijst, maar op zakger is enum
- TypeKadastraalOnroerendeZaak_enum description is leeg behalve het herhalen van de enumeratiewaarden (wat zinloos is)
- nummeraanduidingIdentificatie --> description "tamplated Halling naar de BAG"
- KadastraalOnroerendeZaak_links._links.zakelijkGerechtigden is array, maar kan maar één link zijn (zakelijk gerechtigde heeft geen identificatie en geen endpoint voor opvragen enkele resource).
- TypePersoon_enum gedefinieerd maar niet gebruikt
- KadasterNietNatuurlijkPersoon.metNaamOpenbaarRegister is array met property naam erin. Waarom niet gewoon array van string?
- Beslaglegger allOf volgorde onjuist voor code genereren (class waaruit overorven moet worden, moet als eerste genoemd worden.
- In …
> Review20200224

- specificatie/BRK-Bevragen/openapi.yaml
- Hermodelleren overerving personen
- Persoonadressen als gegevensgroep i.p.v. embedded als subresource (incl. verwijderen expand parameter van persoon endpoints
- ZakelijkGerechtigde.tenaamstellingen --> tenaamstelling
- ZakelijkGerechtigde.persoon gewijzigd
- Tenaamstelling.persoon (kadasterNatuurlijkPersoon, kadasterNietNatuurlijkPersoon, ingeschrevenNatuurlijkPersoon, ingeschrevenNietNatuurlijkPersoon) verwijderd
- In Tenaamstelling toevoegen betrokkenPartner, betrokkenSamenwerkingsverband en betrokkenGorzenEnAanwassen
- Aan ZakelijkGerechtigde_links toevoegen betrokkenPartner, betrokkenSamenwerkingsverband en betrokkenGorzenEnAanwassen
> Hermodelleren personen en zakelijk gerechtigden

- specificatie/BRK-Bevragen/openapi.yaml
de beschrijving bij endpoint /kadastraalonroerendezaken wijzigen, zodat het in lijn is met de implementatie.
De gebruiker moet kiezen welk zoekpad gebruikt wordt, bestaande uit een beperkte combinatie van parameters (waarvan bij dat zoekpad sommige parameters verplicht zijn en andere optioneel). Het combineren van parameters uit meerdere zoekpaden/parametercombinaties is niet toegestaan en zal een 400 bad request leveren.
> description voor parametercombinaties

- specificatie/BRK-Bevragen/openapi.yaml
in de response voor Kadasterpersoon zou er link(s) moeten zijn naar kadastraal onroerende zaken waar de betreffende persoon een rol in heeft
> toevoegen link naar kadastraal onroerende zaak vanuit Kadasterpersoon

- specificatie/BRK-Bevragen/APILAB2603/openapi.yaml
adressen voor personen
in plaats van de 5 verschillende adresproporties voor woon en post, plus voor binnenlands, buitenlands en postbus, is er nu alleen woonadres en postadres, waarbinnen alle properties voor een binnenlands-, buitenlands- of postbusadres zijn opgenomen.
> hermodelleren adressen van personen

- specificatie/BRK-Bevragen/openapi.yaml
Update openapi.yaml
#313 Perceelnummerrotatie en perceelnummerverschuiving weer toegevoegd
#353 Perceelnummerrotatie en perceelnummerverschuiving weer toegevoegd
#254 Path-parameter kadastraalobjectidentificatie hernoemd naar kadastraalonroerendezaakidentificatie + descriptions aangepast
#354 Diverse Path-parameters hernoemd en de property kadastraalobjectidentificatie hernoemd naar identificatie
#253 pattern: "^[A-IK-Z]{1,2}$" toegevoegd aan query-parameter kadastraleaanduiding__sectie.
#257 Bij alle waardelijste een allOff met in de description de verwijzing naar de waardelijst opgenomen.
> 1e stap herstel. 1e commit van 08-04

- specificatie/BRK-Bevragen/openapi.yaml
typeGerechtigde_enum component moet met hoofdletter beginnen, zoals elke schema component
> typeGerechtigde_enum moet met hoofdletter beginnen

- README.md
- link naar getting started
- link naar swaggerhub verwijst naar genereervariant
- contactpersoon Jan Willem Kooi verwijderd
> Readme bijgewerkt

- specificatie/BRK-Bevragen/genereervariant/openapi.yaml
- aanpassingen nav vraag van klant welke imkad versie we gebruikten. Heb de mapping gecheckt en zag dat er nog een paar elementen in staan uit imkad 2.2. Zie https://developer.kadaster.nl/schemas/imkad/20200130/wijzigingen.html
- pattern aanpassing bij validatie huisnummer
- typos
> Aanpassingen in de openapi specs

- specificatie/BRK-Bevragen/genereervariant/openapi.yaml
- specificatie/BRK-Bevragen/openapi.yaml
Naast identificatie is ook property "domein" opgenomen bij resources kadastraalonroerendezaken, kadasternatuurlijkpersonen en kadasternietnatuurlijkpersonen.
Zie #510
> Domein toevoegen aan resource identificaties

- specificatie/BRK-Bevragen/genereervariant/openapi.yaml
- specificatie/BRK-Bevragen/openapi.yaml
Hiermee hebben we deze componentne expliciet gedefinieerd in de openapi.yaml en zijn we niet meer afhankelijk van hoe de resolver dit oplost. 
Enige verschil met de resolver is dat die twee underscores in de naam gebruikt en nu wordt er maar 1 onderscore in de naam gebruikt. 
Zie ook #539 
Closes #539
> In deze pull request de _embedded coponenten van collectie opgenomen

- specificatie/BRK-Bevragen/openapi.yaml
**Informatie:**
https://swagger.io/docs/specification/authentication/api-keys/
Verder heb ik de naam van de header gelijk getrokken met die van de BAG API.
> Security (obv apiKey) toegevoegd aan openapi specificatie

- specificatie/BRK-Bevragen/openapi.yaml
#568 diverse prefixes op query parameternamen weggehaald die niks toevoegden aan de duidelijkheid
#436 toelichting toegevoegd bij betrefMeerOnroerendeZaken en bij indicatieOudeOnroerendeZaakBetrokken
closes #436
> Params prefix weggehaald en toelichting op betrefMeerOnroerendeZaken toegevoegd

- specificatie/BRK-Bevragen/genereervariant/openapi.json
- specificatie/BRK-Bevragen/genereervariant/openapi.yaml
- specificatie/BRK-Bevragen/openapi.yaml
- test/BRK-Bevragen-postman-collection.json
de volgorde van servers in de OAS gewijzigd zodat de eto-apikey bovenaan staat. Dan komt die ook als baseUrl in de gegenereerde postman collection, zodat gebruikers deze direct kunnen gebruiken
> volgorde servers gewijzigd t.b.v. postman collection

- specificatie/openapi.yaml
Toevoegen paginering op /hypotheken en /beslagen, omdat daar redelijk veel resultaten kunnen zijn op een zoekactie.
Fixes #599
> Toevoegen paginering op hypotheken en beslagen endpoints

- specificatie/openapi.yaml
toegevoegd zowel identificatie (onroerendeZaakIdentificatie) en link (rustOpObject)
Ik ben er nu vanuitgegaan dat een zekerheidsstelling (beslag of hypotheek) rust op maximaal 1 Kadastraal object (vraag staat nog open in #600 of dit klopt)
Fixes #600
> toevoegen relatie van hypotheek en beslag naar onroerende zaak waar het op rust

- specificatie/openapi.yaml
Toevoegen endpoints voor het raadplegen van een beslag of hypotheek op de identificatie.
Fixes #601
Zie ook https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/591#issuecomment-671326712
En https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/590#issuecomment-671326387
> Raadpleeg zekerheidsstelling

- code/genereer.sh
aanpassen genereer script om sneller erachter te komen wanneer resolven niet-valide genereervariant/operapi.yaml heeft opgeleverd.
> Na resolven van yaml checken of de genereervariant ook valide is

- .github/workflows/resolve.yml
Bij pull requests treden er errors op omdat de genereervariant van een branch meegaan met de pr.
Hierdoor zijn er geen verschillen in de genereervariant van de branch en de genereervariant die wordt gegenereerd in de pr.
Hierdoor is er niets te committen en faalt de git commit.
Een check is toegevoegd om te controleren of er verschillen zijn voordat de git statements wordt uitgevoerd
> ci: commit alleen als er verschillen zijn in genereervariant om git errors te voorkomen

- Releasenotes.md
- specificatie/domain.yaml
- specificatie/kadaster-natuurlijk-personen.yaml
- specificatie/kadaster-niet-natuurlijk-personen.yaml
- specificatie/kadastraal-onroerende-zaken.yaml
- specificatie/openapi.yaml
- specificatie/zakelijk-gerechtigden.yaml
Inhoudelijk is er in deze patch niets gewijzigd.
De structuur van de yaml-bestanden is aangepast omdat het bestand erg groot en overzichtelijk werd.
Door deze opslitsing is het beheer overzichtelijker en is het werken aan toekomstige wijzigingen beter te managen.
De openapi.yaml in de genereervariant is gewijzigd als gevolg van het gebruiken van een andere generator voor het resolven.
Deze wijzigingen betreffen hoofdzakelijk volgorde wijzigingen van schemacomponenten.
Daarnaast zijn er enkele parameter-properties met default-waarden nu expliciet opgenomen in de genereervariant.
> OpenApi.Yaml opgesplitst in kleinere yaml-bestanden

- specificatie/domain.yaml
component NaamPersoon gemaakt als extensie op Naam, zodat in de naam van de partner (heeftPartnerschap.naam) geen aanschrijfwijze is opgenomen
> component NaamPersoon

- features/aanhef.feature
- features/aanschrijfwijze.feature
- features/gebruik_in_lopende_tekst.feature
- features/voorletters.feature
Naar aanleiding van de implementatie van #375 heb ik typos gefixt in beschrijvingen van:
* `aanhef.feature` 
* `aanschrijfwijze.feature` 
* `gebruik_in_lopende_tekst.feature` 
* `voorletters.feature`. 
---
In het algemeen wordt nu consistent "predikaat" gebruikt en zijn links toegevoegd naar de waardelijst [adellijkeTitelOfPredikaat](https://www.kadaster.nl/schemas/waardelijsten/AdellijkeTitelOfPredikaat/). 
De laatste regel voor het bepalen van de voorletters (".") is verduidelijkt en toegevoegd aan de scenario's.
Tot slot:
• `aanhef.feature` aanschrijfwijze (= aanhef) en voornamen (= niet gebruikt) werden per abuis gebruikt
• `gebruik_in_lopende_tekst.feature` voornamen (= niet gebruikt) en AH (= GA) werden per abuis gebruikt
> Fix typos in features versie 1.2.0

- .gitignore
- .spectral.yml
- package-lock.json
- package.json
Bij een commit wordt gecontroleerd of de openapi.yaml voldoet aan de oas style guide gedefinieerd in Haal Centraal Common. 
Op dit moment is de rule 'oas3-valid-oas-content-example' uitgezet omdat er nog fouten zitten in de common.yaml. Door deze rule op on te zetten of weg te halen, kan getest worden dat het dan niet meer lukt om te committen.
De linter kan ook worden gedraaid door de statement `npm run oas:lint' uit te voeren.
Lokaal resolven en valideren van de gegenereerde variant toegevoegd
> Feature: pre-commit oas valideren

- specificatie/beslagen.yaml
- specificatie/domain.yaml
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- specificatie/hypotheken.yaml
- specificatie/kadaster-natuurlijk-personen.yaml
- specificatie/kadaster-niet-natuurlijk-personen.yaml
- specificatie/kadastraal-onroerende-zaken.yaml
- specificatie/openapi.yaml
- specificatie/privaat-rechtelijke-beperkingen.yaml
- specificatie/publiek-rechtelijke-beperkingen.yaml
- specificatie/zakelijk-gerechtigden.yaml
- Bump `Haal-Centraal-Common` links naar v1.2.0
- Toevoegen van global tags t.b.v. linter warning
> chore: bump haal centraal common links naar v1.2.0

- specificatie/beslagen.yaml
- specificatie/domain.yaml
- specificatie/hypotheken.yaml
Ik heb de componentnamen "AntekeningBeperkt",  "Aantekening"  en "AantekeningDeprecated". Ik sta open voor verbetervoorstellen.
Verder is begrenzing een ref naar een opengisdefinitie. Daar mag geen sibling naast. Ik heeb dus de deprecated toegevoegd met een allOf. @MelvLee : wil jij checken of dat codegeneratie-issues geeft ? Ook hier ben ik benieuwd of iemand een betere constructiue weet.
> Wijzigingen aan de Aantekening-structuur n.a.v. #720

- specificatie/domain.yaml
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
De velden datumSluiting en datumOntbinding zullen worden verwijderd in een toekomstige versie van IMKAD. 
Hierop heeft onze bron al voorgesorteerd en deze levert nu al deze velden niet meer.
Mijn voorstel is om deze velden als deprecated te markeren, zodat we deze ook kunnen uitfaseren in een toekomstige release.
@JohanBoer: kun jij nagaan of ik het zo goed heb gedaan met het toevoegen van de deprecated param?
> Velden datumSluiting en datumOntbinding op deprecated van Partnerschap

- specificatie/domain.yaml
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
- specificatie/kadastraal-onroerende-zaken.yaml
- specificatie/openapi.yaml
- specificatie/publiek-rechtelijke-beperkingen.yaml
- specificatie/stukken.yaml
- specificatie/zakelijk-gerechtigden.yaml
- test/BRK-Bevragen-postman-collection.json
- Probleem met HalLin_2 opgelost (was een verwijzing naar een oude "common"-versie 
- Stukken en stukdelen waren onterecht toegevoegd aan de zakelijkgerechtigdeHalCollectieEmbedded. --> Verwijderd
- ZakelijkGerechtigdeLinks --> isGebaseerOpStukdeel was een array. Nu een enkele link
- property Kadasterverzoek.Redenenverzoek --> Kadasterverzoek.redenenverzoek 
- PubliekrechtelijkeBeperkingen --> Stukidentificaties en link naar stukken (array) toegevoegd. Stukdelen nog laten staan.(Marcel zoekt dit uit) 
- Tag Stukdelen verwijderd
- Stuktype_enmum --> StuktypeEnum (Description volgt nog)
- Stuk.tekeningIngeschreven --> Stuk.indicatieTekeningBijgevoegd + description aangepast
- Descriptions omgezet naar markdown voor Stukken en Stukdelen
- Stukken uit KadastraalOnroerendeZaakEmbedded …
> Aanpassingen n.a.v. bepreking 18-11 doorgevoerd

- specificatie/domain.yaml
- specificatie/genereervariant/openapi.json
- specificatie/genereervariant/openapi.yaml
het voorbeeld gebruikt de straatnaam. Dat is niet correct, want moet de korteNaam gebruiken. Anders past het niet op een envelop of binnen een envelopvenster
> correctie adresregel1 example

- package.json
Twee scripts toegevoegd waarmee de gegenereerde bestanden
- uit staging worden gehaald (unstage-generated)
- worden teruggedraaid (rollback-generated)
De unstage-generated wordt in pre-commit aangeroepen zodat de gegenereerde bestanden niet worden gecommit. Dit gebeurt namelijk remote
> ci: unstage generated files before commit

- features/filiatie.feature
Feature die het opnemen van de filiatie gegevens illustreert.
Deze versie heeft nog:
- geen onroerende zaak identificaties ingevuld, ik hoop hiervoor binnenkort onroerende zaken te vinden in de acceptatie omgeving
- wel indicatieSluimerend in bijbehorendeAppartementsrechtIdentificaties, maar @kad-pothot heeft aangegeven dat dit in release v1.3 nog niet kan worden geleverd
> filiatie feature toegevoegd

- specificatie/kadastraal-onroerende-zaken.yaml
Vraag: Ik heb alleen de query-parameter toegevoegd. Volgens mij willen we niet dat we deze aanduiding met gemeentecode ook toevoegen aan de resource KadastraalOnroerendeZaak. Dat wil ik even checken.
> Queryparameter kadastraleAanduidingMetGemeentecode toegevoegd

- specificatie/domain.yaml
- specificatie/zakelijk-gerechtigden.yaml
Bij het doorvoeren vroeg ik mij af of ik nu bij de zakelijk gerechtigde_links ook een link moet opnemen naar het appartementsrecht waar het gesplitste recht van de zakelijkgerechtigde betrekking op heeft. Anders heb je nergens een verwijzing naar het gesplitste appartementsrecht. 
Ik heb nu allen doorgevoerd wat we besproken hebben. Bovenstaande link is dus nog niet opgenomen.
> Zakelijkgerechtigden n.a.v. splitsingen.  Aanpassing zoals vorige week woensdag besproken doorgevoerd

- .github/workflows/generate-user-stories.yml
- README.md
- docs/_config.yml
- docs/getting-started.md
- docs/index.md
- docs/releasenotes.md
Bevat voornl. aanpassingen t.b.v. de GitHub Pages omgeving.
Graag aandacht voor:
* In zowel README.md en index.md staat de zin<br/><br/>_"Komende periode wordt de API uitgebreid met andere erfpachters. Dat zijn de eigenaren van de appartementsrechten die uit erfpacht zijn ontstaan. Ook worden sluimerende appartementsrechten zichtbaar gemaakt (v1.5)."_<br/><br/>Deze moet vervangen worden zodat duidelijk is wat men straks in de 2.0 kan verwachten.
* getting-started.md
Ik heb het idee dat de beschikbare resources niet zijn gewijzigd maar graag een check daarop.
Ook de testgevallen moeten wellicht aangepast worden.
* goals-canvas.md moet wellicht worden aangepast.
* releasenotes.md moeten worden aangepast.
> Aanpassingen documentatie m.b.t. 1.5 versie

- README.md
- docs/getting-started.md
- docs/index.md
O.a.:
* Check op links en teksten
- In README.md
- Geen individuele e-Mailadressen meer in de 'Contacten' paragraaf;
- Inhoud gelijk gemaakt aan 'index.md' (main pagina van GitHub Pages);
- index.md (main pagina van GitHub Pages)
- De link 'Stelselcatalogus' werkte niet meer. Deze verwees naar:<br/><br/>*https://www.stelselcatalogus.nl/registraties/BRK/*<br/><br/>maar moet waarschijnlijk verwijzen naar:<br/><br/>*https://www.stelselcatalogus.nl/registraties/registratie?id=http://opendata.stelselcatalogus.nl/id/registratie/BRK*<br/><br/>Dit heb ik in deze PR aangepast maar graag even aangeven of dit klopt;
- Getting Started
- Onder 'Probeer en test de API' staat de tekst:<br/><br/>*We hebben al een project voor je gemaakt die je kan gebruiken: BRK-Bevragen-postman-collection.json. Hierin …
> Correctie op links en teksten
