VNG-Realisatie/Haal-Centraal-BRK-bevragen

specificatie/openapi.yaml
Ik heb een eerste versie van de OAS3 gemaakt. Die levert stof voor discussie op. De vraag is hoe diep we gaan embedden en wat de ingang voor het opvragen van kadastrale prodcuten wordt. Daarnaast gaarne discussie over de definitie van de resources. Dat is mijns inziens nu op een te abstract niveau gedaan.
Dit is de eerste aanzet om #8 te realiseren
=> Eerste poging OAS3. Vooral voer voor discussie

README.md
Aanpassen van de Read.me om de locatie van de oas3 in swagger-format te tonen.
=> Aanpassing Read,me

specificatie/openapi.yaml
Er zijn nog enkele discussies t.a.v. de wijze waarop we polyformie op moeten lossen. Er zijn een aantal exclusive-OR relaties geïmplementeerd. De relatie t.a.v. natuurlijkPersoon en nietNatuurlijkPersoon bij tenaamstelling is voorzien van een oplossingsvoorstel. Zie voor nadere toelichting #93
=> Aangepaste OAS3 n.a.v. #93

specificatie/openapi.yaml
OAS3 is wel Valid, maar nog enkele structuur fouten moeten hersteld worden.
=> Diverse wijzigingen voor sprint 5 doorgevoerd

specificatie/openapi.yaml
N.a.v. review door Frank.
Ps, wijzigingen die door Marcel zijn voorgesteld volgen nog.
=> Aanpassingen aan openapi.yaml

docs/getting-started-brkbevragen.md, docs/getting-started-zoekenpersoon.md
Getting started documenten voor de apis:
BRK bevragen API
ZoekenPersoon API
=> Getting started documenten

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
Nadat Melvin de branch MelvLee-patch-2020.02.07 gemaakt heeft is eer een Major constructie aanpassing gedaan. De resolvde versie en de unresolved versie zijn daarna van plaats verwisseld. Daardoor onstonden er conflicts bij het megren van de Pull-request. Ik heb nu buiten Github een diff gedaan tussen de actuele versie en de versie die Melvin heeft aangeleverd. 
Dat leverde geen issues op. De door Melvin voorgestelde wijzigingen zitten in deze Pull request.
=> Wijzigingen die Melvin in branch MelvLee-patch-2020.02.07 nu doorgevoerd zonder conflicts

README.md
Links naar resolved en unresolved gecorrigeerd en link naar waardelijsten API toegevoegd
=> Links in readme gecorrigeerd n.a.v. wijzigen locatie resolved/unresolved

README.md
=> correctie van readme link unresolved

specificatie/BRK-Bevragen/openapi.yaml
=> typeGerechtigde moet een enumeratie zijn

specificatie/BRK-Bevragen/openapi.yaml
en identificatie van een Stuk naar AbstractStuk (#281)
=> weghalen oneOf constructies

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
N.a.v. #330 heb ik zakelijkgerechtigden bij de _links toegevoegd. Tevens heb ik al property de arrays voor kadastraalonroerendezaakidentificaties en de zakelijkgerechtigdenidentificaties toegevoegd.
closes #330
=> Johan boer   links persoon #330

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
#313 Perceelnummerrotatie en perceelnummerverschuiving weer toegevoegd
#352 Perceelnummerrotatie en perceelnummerverschuiving weer toegevoegd
#254 Path-parameter kadastraalobjectidentificatie hernoemd naar kadastraalonroerendezaakidentificatie + descriptions aangepast
#354 Diverse Path-parameters hernoemd en de property kadastraalobjectidentificatie hernoemd naar identificatie
#253 pattern: "^[A-IK-Z]{1,2}$" toegevoegd aan query-parameter kadastraleaanduiding__sectie.
#257 Bij alle waardelijste een allOff met in de description de verwijzing naar de waardelijst opgenomen. 
closes #313 
closes #352 
closes #254 
closes #354 
closes #253 
closes #257
closes #309
=> Johan boer   kleine aanpassingen

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
Reverts VNG-Realisatie/Haal-Centraal-BRK-bevragen#377
=> Revert "Johan boer  geometry zuiverder specificeren n.a.v. #298"

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
Reverts VNG-Realisatie/Haal-Centraal-BRK-bevragen#378
=> Revert "Johan boer   links persoon #330"

specificatie/BRK-Bevragen/openapi.yaml
Update openapi.yaml
Alle geometrie verwijzingen naar de opengis definities laten verwijzen.
=> 2e stap herstel 08-04 geometry verwijzingen.

specificatie/BRK-Bevragen/openapi.yaml
Aanpassing in de kadasterNatuurlijkPersoon en KadasterNietNatuurlijkP…
…ersoon
N.a.v. #330 heb ik zakelijkgerechtigden bij de _links toegevoegd. Tevens heb ik al property de arrays voor kadastraalonroerendezaakidentificaties en de zakelijkgerechtigdenidentificaties toegevoegd.
=> 3e stap herstel 08-04

specificatie/BRK-Bevragen/openapi.yaml
Bij alle verwijzingen naar waarderlijst de allOf verwijderd.
=> 4e stap herstel verwijzingen naar waardelijst

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
=> Jbo #332 en #292 Descriptions aangepast

specificatie/BRK-Bevragen/openapi.yaml
=> verwijderen inOnderzoek uit adres van een persoon

specificatie/BRK-Bevragen/openapi.yaml
=> Description identificatie aangepast + kvknummer en rsin toegevoeg #398

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
De lokatie van de waardelijsten toegevoegd aan de descriptions van de componenten waarin de waardelijsten voorkomen. 
closes #399
=> Descriptions waardelijsten #399

specificatie/BRK-Bevragen/openapi.yaml
Wijzigingen doorgevoerd n.a.v. testbevindingen.
closes #478 
closes #477 
closes #460 
closes #458
=> Implementatiefeedback

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
=> Identificatie van persoon kan RSIN zijn

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
Wijzigingen n.a.v. wijzigingen t.o.v. de final draft van IMKAD doorgevoerd. 
In de resolved versie zijn ook wijzigingen uit andere pull request nu mee-gegenereerd. 
closes #502
=> Wijzigingen n.a.v.#502 doorgevoerd 

specificatie/BRK-Bevragen/openapi.yaml
=> nen3610 domein toegevoegd

specificatie/BRK-Bevragen/openapi.yaml
Reverts VNG-Realisatie/Haal-Centraal-BRK-bevragen#511
in versie 1.0 zit dit nog niet. wordt in versie 1.1 toegevoegd
=> Revert "nen3610 domein toegevoegd"

specificatie/BRK-Bevragen/openapi.yaml
#523: begrenzingDienendErf & begrenzingHeersendErf verwijderd uit Aantekening 
+ server-url aangepast
=> #523: begrenzingDienendErf & begrenzingHeersendErf verwijderd uit OAS

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
Ik heb de verwijzingen naar de common.yaml aangepast naar v1.0.0 en op basis daarvan opnieuw de genereervariant geresolved. Als deze wijzigingen ok zin en gemerged mogen worden zal ik daarna release v1.0.0 aanmaken.
=> Laatste puntjes op de i

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
huisnummerToevoeging moet zijn huisnummertoevoeging conform BAG
n.a.v. #542
=> correctie huisnummerToevoeging naar huisnummertoevoeging

features/levering-koopsom.feature
=> correctie identificaties koopsom feature

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
Tevens de genereervariant opnieuw geresolved en aangeboden
closes #569
=> Aanpassen casing van queryparameters n.a.v. #569

specificatie/BRK-Bevragen/genereervariant/openapi.yaml, specificatie/BRK-Bevragen/openapi.yaml
X-Rate headers verwijderd n.a.v. #579 
genereervariant opnieuw geresolved n.a.v. recente pull requests.
=> Headersverwijderen579

docs/getting-started.md, specificatie/BRK-Bevragen/openapi.yaml, test/BRK-Bevragen-postman-collection.json
Wat is aangepast:
- openapi.yaml: de server-urls voor de PRODUCTIE & TEST omgeving aangepast
- getting-started.md: hoe aan te sluiten op PRODUCTIE & TEST omgeving aangepast
- brk-bevragen-postman-collection.json: geupdated, zodat deze weer aansluit op de laatste versie van de openapi.yaml.
=> Aanpassingen voor BRKBevragen v1.1

code/README.md, docs/getting-started.md, test/cases/README.md
- aan getting started verwijzing naar client code toegevoegd
- readme bij de code
- readme bij de testgevallen
=> Code verwijzingen en uitleg toegevoegd

README.md
N.a.v. mail van forum standaardisatie.
=> foutieve relatieve links in readme hersteld.

specificatie/openapi.yaml
=> Toevoegen HAL-links aan embedded publiekrechtelijkeBeperkingen in KOZ

features/aanhef.feature, features/aanschrijfwijze.feature, features/gebruik_in_lopende_tekst.feature, features/voorletters.feature
De features beschrijven hoe deze velden in de naam van een Kadasternatuurlijkpersoon moeten worden gevuld
=> Toevoegen features voor aanschrijfwijze, aanhef en gebruikInLopendeTekst

specificatie/domain.yaml, specificatie/hypotheken.yaml
Een deel van #659 was al in Marcel's aanpassingen doorgevoerd.
=> Descriptions m.b.t. hypotheekhouder aangepast nav #659

specificatie/openapi.yaml
Toevoegen zoeken van een kadastraal onroerende zaak op locatie (geometrisch punt) of contour (geometrische polygoon).
Fixes #451 
Fixes #171 
Fixes #165
Fixes #155
Let op: nog onduidelijk of dit in release 1.2 of in release 1.3 zal worden opgenomen
=> Zoeken koz geometrie

specificatie/genereervariant/openapi.json, specificatie/genereervariant/openapi.yaml, specificatie/zakelijk-gerechtigden.yaml
toevoegen accept-crs en content-crs aan zakelijkgerechtigden
n.a.v. #633
=> Zakelijkgerechtigden crs

specificatie/genereervariant/openapi.json, specificatie/genereervariant/openapi.yaml, specificatie/publiek-rechtelijke-beperkingen.yaml
Beperkingsgebied verwijderd uit PB.
=> Beperkingsgebied verwijderd uit PubliekrechtelijkeBeperking.

specificatie/openapi.yaml
=> Toevoegen link naar document (blob, bijv. pdf) van een Kadasterstuk

specificatie/domain.yaml
Adres-definitie uit de BAG hergebruitk + examples aangepast nav #561
=> Hergebruik van de adresdefinitie uit de BAG-repository

specificatie/privaat-rechtelijke-beperkingen.yaml
=> Parameter acceptCrs en responseheader Content-Crs toegevoegd

specificatie/privaat-rechtelijke-beperkingen.yaml
=> alOff zonder toegevoegde properties verwijderd nav

specificatie/beslagen.yaml, specificatie/hypotheken.yaml
@CathyDingemanse : Wil jij de property-namen en de descriptions beoordelen ?
=> Hypotheek beslagbedrag648

specificatie/beslagen.yaml, specificatie/domain.yaml, specificatie/hypotheken.yaml, specificatie/kadaster-natuurlijk-personen.yaml, specificatie/kadaster-niet-natuurlijk-personen.yaml, specificatie/kadastraal-onroerende-zaken.yaml, specificatie/privaat-rechtelijke-beperkingen.yaml, specificatie/publiek-rechtelijke-beperkingen.yaml, specificatie/zakelijk-gerechtigden.yaml
=> inline embedde object als schemacomponenten gedefinieerd nav #702

features/aanhef.feature, features/gebruik_in_lopende_tekst.feature
Aanhef en gebruikInLopendeTekst met correcte genderneutrale vorm bij onbekend geslacht
n.a.v. https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/375#issuecomment-707174182
=> Genderneutraal

code/java/api/openapi.yaml, specificatie/domain.yaml, specificatie/genereervariant/openapi.json, specificatie/genereervariant/openapi.yaml
=> Feature/#711 Description toegevoegd aan KadastraalOnroerendeZaak

specificatie/domain.yaml
Aangepast op basis van #720 
closes #720
=> Aantekening gewijzigd n.a.v. #720

docs/releasenotes.md, specificatie/beslagen.yaml, specificatie/domain.yaml, specificatie/genereervariant/openapi.json, specificatie/genereervariant/openapi.yaml, specificatie/hypotheken.yaml, specificatie/kadaster-natuurlijk-personen.yaml, specificatie/kadaster-niet-natuurlijk-personen.yaml, specificatie/kadastraal-onroerende-zaken.yaml, specificatie/openapi.yaml, specificatie/privaat-rechtelijke-beperkingen.yaml, specificatie/publiek-rechtelijke-beperkingen.yaml, specificatie/stukken.yaml, specificatie/zakelijk-gerechtigden.yaml
Specificatie te raadplegen via https://petstore.swagger.io/?url=https://raw.githubusercontent.com/JohanBoer/Haal-Centraal-BRK-bevragen/develop/specificatie/genereervariant/openapi.yaml#/Beslagen/GetBeslagenKadastraalOnroerendeZaak
=> Releasenotes + besproken wijzigingen voor versie 1.3

specificatie/domain.yaml, specificatie/genereervariant/openapi.json, specificatie/genereervariant/openapi.yaml, specificatie/stukken.yaml
=> kadastraalOnroerendeZaken verwijder uit stukdeelLinks nav #777 en #807

docs/releasenotes.md, specificatie/domain.yaml, specificatie/genereervariant/openapi.json, specificatie/genereervariant/openapi.yaml
Door het hergebruik van AantekeningBasis in zowel hypotheek als beslag heb ik een oplossing bedacht die jullie wel even goed moeten reviewen. Volgens SwaggerHub is deze constructie valide.
=> Wijzigingen n.a.v. #793

specificatie/domain.yaml
=> Einddatum KOZ verwijderd n.a.v. overleg 30-06-2021

specificatie/domain.yaml
Ik heb nu alle 5 dataelementen toegevoegd. 
Er was gevraagd om:
Register
Deel
Nummer
Reeks 
In het IMKAD is er sprake van dataelementen registerCode en een soortRegister. Deze verwijzen ieder naar een aparte waardelijst. 
Vooralsnog heb ik allebei deze properties opgenomen.
=> DeelEnNummer toegevoegd bij component Stuk

specificatie/domain.yaml, specificatie/genereervariant/openapi.json, specificatie/genereervariant/openapi.yaml
=> velden isOvergegaanIn & isOntstaanUit gewijzigd van Filiatie[] naar Filiatie

specificatie/domain.yaml, specificatie/genereervariant/openapi.json, specificatie/genereervariant/openapi.yaml
=> IndicatieVervallen veld verwijderd bij PerceelFiliatie

docs/zakelijk-gerechtigden-uit-splitsing.md, raadplegen-zakelijk-gerechtigden-gesplitste-van-kadastraal-onroerende-zaak.feature
In deze feature file heb ik geprobeerd de invulling van de nieuwe properties en parameter te beschrijven.
=> feature: raadplegen zakelijk gerechtigden van gesplitste kadastraal onroerende zaak

docs/getting-started.md
=> toevoegen verwijzing naar testcases vanuit getting started
